controller_list:
  - name: fake_kmr_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - kmr_joint_1
      - kmr_joint_2
      - kmr_joint_3
      - kmr_joint_4
      - kmr_joint_5
      - kmr_joint_6
      - kmr_joint_7
  - name: fake_kmr_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - gripper_finger_joint
initial:  # Define initial robot poses per group
  - group: kmr_arm
    pose: random_pose
  - group: kmr_gripper
    pose: gripper_open