arm_position_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - kmr_joint_1
    - kmr_joint_2
    - kmr_joint_3
    - kmr_joint_4
    - kmr_joint_5
    - kmr_joint_6
    - kmr_joint_7
  gains:
    kmr_joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kmr_joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kmr_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kmr_joint_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kmr_joint_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kmr_joint_6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kmr_joint_7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1