controller_list:
  - name: fake_kmr_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - kmriiwa_joint_1
      - kmriiwa_joint_2
      - kmriiwa_joint_3
      - kmriiwa_joint_4
      - kmriiwa_joint_5
      - kmriiwa_joint_6
      - kmriiwa_joint_7
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - finger_joint
initial:  # Define initial robot poses per group
  - group: kmr_arm
    pose: default_arm_pose
  - group: gripper
    pose: gripper_open