kmr_arm_position_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - kmriiwa_joint_1
    - kmriiwa_joint_2
    - kmriiwa_joint_3
    - kmriiwa_joint_4
    - kmriiwa_joint_5
    - kmriiwa_joint_6
    - kmriiwa_joint_7
  gains:
    kmriiwa_joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kmriiwa_joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kmriiwa_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kmriiwa_joint_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kmriiwa_joint_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kmriiwa_joint_6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kmriiwa_joint_7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1