controller_list:
  - name: kmr_arm_position_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - kmriiwa_joint_1
      - kmriiwa_joint_2
      - kmriiwa_joint_3
      - kmriiwa_joint_4
      - kmriiwa_joint_5
      - kmriiwa_joint_6
      - kmriiwa_joint_7